name: Build and Deploy React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Schritt 1: Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      # Schritt 2: Node.js einrichten
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Schritt 3: Abhängigkeiten installieren
      - name: Install dependencies
        run: npm install

      # Schritt 4: Build der Anwendung
      - name: Build the project
        run: npm run build

      # Schritt 5: Deployment auf GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
